create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  location_key text not null unique,
  name text not null,
  lat double precision not null,
  lon double precision not null
);

create table if not exists public.devices (
  id bigint generated by default as identity primary key,
  device_uid text not null unique,
  board_model text not null default 'Arduino UNO Q',
  firmware_version text,
  created_at timestamptz not null default now()
);

create table if not exists public.metric_types (
  id smallint generated by default as identity primary key,
  code text not null unique,
  unit text not null,
  description text not null
);

create table if not exists public.readings (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.locations(id),
  device_id bigint not null references public.devices(id),
  status smallint not null check (status between 0 and 2),
  measured_at_ms bigint not null,
  created_at timestamptz not null default now()
);

create table if not exists public.reading_metrics (
  reading_id bigint not null references public.readings(id) on delete cascade,
  metric_type_id smallint not null references public.metric_types(id),
  metric_value double precision not null,
  primary key (reading_id, metric_type_id)
);

create index if not exists idx_readings_location_ts
  on public.readings (location_id, measured_at_ms desc);

create index if not exists idx_metrics_type
  on public.reading_metrics (metric_type_id);

insert into public.metric_types (code, unit, description)
values
  ('ph', 'pH', 'Potential hydrogen'),
  ('ntu', 'NTU', 'Turbidity proxy'),
  ('tds', 'ppm', 'Total dissolved solids'),
  ('temp_c', 'C', 'Ambient temperature'),
  ('humidity', '%', 'Relative humidity')
on conflict (code) do update
set unit = excluded.unit,
    description = excluded.description;

create or replace function public.ingest_water_reading(
  p_location_key text,
  p_location_name text,
  p_lat double precision,
  p_lon double precision,
  p_device_uid text,
  p_status smallint,
  p_measured_at_ms bigint,
  p_ph double precision default null,
  p_ntu double precision default null,
  p_tds double precision default null,
  p_temp_c double precision default null,
  p_humidity double precision default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_location_id bigint;
  v_device_id bigint;
  v_reading_id bigint;
begin
  insert into public.locations (location_key, name, lat, lon)
  values (p_location_key, p_location_name, p_lat, p_lon)
  on conflict (location_key) do update
  set name = excluded.name,
      lat = excluded.lat,
      lon = excluded.lon
  returning id into v_location_id;

  insert into public.devices (device_uid)
  values (p_device_uid)
  on conflict (device_uid) do update
  set device_uid = excluded.device_uid
  returning id into v_device_id;

  insert into public.readings (location_id, device_id, status, measured_at_ms)
  values (v_location_id, v_device_id, p_status, p_measured_at_ms)
  returning id into v_reading_id;

  if p_ph is not null then
    insert into public.reading_metrics (reading_id, metric_type_id, metric_value)
    select v_reading_id, id, p_ph from public.metric_types where code = 'ph';
  end if;

  if p_ntu is not null then
    insert into public.reading_metrics (reading_id, metric_type_id, metric_value)
    select v_reading_id, id, p_ntu from public.metric_types where code = 'ntu';
  end if;

  if p_tds is not null then
    insert into public.reading_metrics (reading_id, metric_type_id, metric_value)
    select v_reading_id, id, p_tds from public.metric_types where code = 'tds';
  end if;

  if p_temp_c is not null then
    insert into public.reading_metrics (reading_id, metric_type_id, metric_value)
    select v_reading_id, id, p_temp_c from public.metric_types where code = 'temp_c';
  end if;

  if p_humidity is not null then
    insert into public.reading_metrics (reading_id, metric_type_id, metric_value)
    select v_reading_id, id, p_humidity from public.metric_types where code = 'humidity';
  end if;

  return v_reading_id;
end;
$$;
